version: '3.8'
services:
  gitlab-server:
    image: 'gitlab/gitlab-ce'
    container_name: my-gitlab-server
    hostname: my-gitlab-server
    restart: always
    ports:
      - "8000:80"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password']= "Siam@123456789@3214"
        puma['worker_processes']=0
        external_url 'http://my-gitlab-server'


    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab      


  gitlab-runner:
    image: 'gitlab/gitlab-runner'
    container_name: 'my-gitlab-runner'
    restart: always
    depends_on:
      - gitlab-server
    volumes:
       - ./gitlab-runner/config:/etc/gitlab-runner
       - /var/run/docker.sock:/var/run/docker.sock
    privileged: true          
